/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    shows: Show;
    links: Link;
    releases: Release;
    'rider-requests': RiderRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    shows: ShowsSelect<false> | ShowsSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    'rider-requests': RiderRequestsSelect<false> | RiderRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'link-hub': LinkHub;
  };
  globalsSelect: {
    'link-hub': LinkHubSelect<false> | LinkHubSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Texte und Bilder für Home und About pflegen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Nur zur Orientierung im CMS, z. B. Home oder About.
   */
  title: string;
  /**
   * Wird beim ersten Speichern automatisch aus dem Seitennamen erzeugt.
   */
  slug: string;
  /**
   * Bestimmt, welche Inhaltsfelder angezeigt werden.
   */
  section: 'home' | 'about' | 'other';
  /**
   * Überschrift der Home-Seite, z. B. SCTTRD.
   */
  headline?: string | null;
  /**
   * Kurzer Zusatz unter der Home-Überschrift.
   */
  subtitle?: string | null;
  /**
   * Deutsche Bio für Home.
   */
  bio_de?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Englische Bio für About.
   */
  bio_en?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Unterüberschrift für About.
   */
  subheading?: string | null;
  /**
   * Kurzer Claim, z. B. „Brutal, aber schön.“
   */
  text?: string | null;
  /**
   * Kontaktadresse für Footer und Navigation.
   */
  email?: string | null;
  /**
   * Überschrift des Booking-Bereichs auf Home.
   */
  ctaHeadline?: string | null;
  /**
   * Beschriftung des Booking-Buttons.
   */
  ctaButton?: string | null;
  /**
   * Betreff der Mail, die über den CTA geöffnet wird.
   */
  ctaButtonEmailSubject?: string | null;
  /**
   * Hauptbild der About-Seite.
   */
  image?: (number | null) | Media;
  /**
   * Kurze Beschreibung für Barrierefreiheit.
   */
  imageAlt?: string | null;
  /**
   * Bilder, die auf der Galerie-Seite erscheinen.
   */
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Nur relevant, wenn mehrere Seiten im selben Bereich sortiert werden.
   */
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shows".
 */
export interface Show {
  id: number;
  venue: string;
  city: string;
  /**
   * Format: DD.MM.YYYY
   */
  date: string;
  status: 'upcoming' | 'past';
  image?: (number | null) | Media;
  imageAlt?: string | null;
  link?: string | null;
  /**
   * Ticket = echter Ticketshop · Webseite = Venue-/Eventseite (kein Ticketverkauf) · Video = Recording
   */
  linkKind?: ('ticket' | 'website' | 'video') | null;
  /**
   * Acts des gemeinsamen Line-ups mit offiziellen Artist-Links und Quelle
   */
  lineup?:
    | {
        name: string;
        /**
         * Offizielle Artist- oder Social-URL
         */
        url?: string | null;
        /**
         * Beleg, z. B. Festival-Line-up
         */
        sourceUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * Zuordnung: auf welcher Seite erscheint die Show (z. B. Home)
   */
  page?: (number | null) | Page;
  updatedAt: string;
  createdAt: string;
}
/**
 * Links im Menü/Footer (Instagram, Spotify, SoundCloud …)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  /**
   * Automatisch aus dem Link übernommen
   */
  title?: string | null;
  /**
   * Anzeigename — automatisch aus dem Link übernommen
   */
  label?: string | null;
  platform?: ('instagram' | 'tiktok' | 'spotify' | 'soundcloud' | 'youtube' | 'other') | null;
  /**
   * https://…
   */
  url: string;
  /**
   * Cover-URL — automatisch via Link-Scrape, manuell überschreibbar
   */
  cover?: string | null;
  /**
   * Letzter erfolgreicher Scrape
   */
  scrapedAt?: string | null;
  target?: ('_blank' | '_self') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ein Eintrag steuert Landingpage, Linkhub und das optionale Homepage-Banner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  title: string;
  /**
   * Wird beim ersten Speichern automatisch aus dem Titel erzeugt.
   */
  slug: string;
  releaseDate: string;
  /**
   * Das Cover für Release-Seite, Linkhub und Banner.
   */
  cover: number | Media;
  description?: string | null;
  /**
   * Nur diesen einen Link eintragen. Die endgültige Spotify-URL kann später ersetzt werden.
   */
  spotifyUrl?: string | null;
  bannerEnabled?: boolean | null;
  /**
   * Vor dem Release ist das Banner sofort sichtbar, danach standardmäßig 28 Tage.
   */
  bannerDurationDays?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Wer hat Rider-PDF und Hospitality Rider angefordert (Name, Venue, E-Mail, Zeitpunkt).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rider-requests".
 */
export interface RiderRequest {
  id: number;
  name: string;
  /**
   * Venue / Veranstaltung
   */
  venue: string;
  email: string;
  file?: 'rider' | null;
  source?: string | null;
  userAgent?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'shows';
        value: number | Show;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'rider-requests';
        value: number | RiderRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  section?: T;
  headline?: T;
  subtitle?: T;
  bio_de?: T;
  bio_en?: T;
  subheading?: T;
  text?: T;
  email?: T;
  ctaHeadline?: T;
  ctaButton?: T;
  ctaButtonEmailSubject?: T;
  image?: T;
  imageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shows_select".
 */
export interface ShowsSelect<T extends boolean = true> {
  venue?: T;
  city?: T;
  date?: T;
  status?: T;
  image?: T;
  imageAlt?: T;
  link?: T;
  linkKind?: T;
  lineup?:
    | T
    | {
        name?: T;
        url?: T;
        sourceUrl?: T;
        id?: T;
      };
  order?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  platform?: T;
  url?: T;
  cover?: T;
  scrapedAt?: T;
  target?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  releaseDate?: T;
  cover?: T;
  description?: T;
  spotifyUrl?: T;
  bannerEnabled?: T;
  bannerDurationDays?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rider-requests_select".
 */
export interface RiderRequestsSelect<T extends boolean = true> {
  name?: T;
  venue?: T;
  email?: T;
  file?: T;
  source?: T;
  userAgent?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Profil, SEO und Anzeigeeinstellungen fuer die ArtisTree-/Linktree-Seite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link-hub".
 */
export interface LinkHub {
  id: number;
  profile: {
    handle: string;
    title: string;
    description: string;
    image?: (number | null) | Media;
  };
  appearance?: {
    theme?: ('red' | 'black' | 'white') | null;
    showUpcoming?: boolean | null;
  };
  seo?: {
    /**
     * Browser-Titel und OpenGraph-Titel
     */
    title?: string | null;
    /**
     * Meta- und OpenGraph-Beschreibung
     */
    description?: string | null;
  };
  /**
   * Nur die Spotify-Track-URL eintragen. Titel, Cover und Kuenstler werden automatisch geladen.
   */
  featuredRelease?: {
    spotify?: string | null;
  };
  bookingEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link-hub_select".
 */
export interface LinkHubSelect<T extends boolean = true> {
  profile?:
    | T
    | {
        handle?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  appearance?:
    | T
    | {
        theme?: T;
        showUpcoming?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  featuredRelease?:
    | T
    | {
        spotify?: T;
      };
  bookingEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}